name = "uptimeflare"
compatibility_date = "2025-04-02"
compatibility_flags = [ "nodejs_compat" ]

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "UPTIMEFLARE_D1"
database_name = "huanlecun-uptimeflare"
database_id = "9d2a5373-b6be-4103-8adc-c9efe88456f2"
